version: "3.6"

services:

  mysql:
    container_name: mysql-db
    image: mysql:8.0.31
    environment:
      - MYSQL_DATABASE=bicicletas
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=bicicletas
      - MYSQL_PASSWORD=secret
    ports:
      - 3306:3306
    volumes:
      - ./scripts:/scripts
      - ./scripts-init.db:/docker-entrypoint-initdb.d

